using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Unpoly.Blazor.Shadcn.Tools;

internal static partial class GeneratedCommands
{
    public static int GenerateApi(DirectoryInfo root, string[] options)
    {
        var output = Path.Combine(root.FullName, "skills", "shadcn-unpoly", "API.md");
        var builder = new StringBuilder();
        builder.AppendLine("<!-- GENERATED by the gen-api .NET command - do not edit. Run the command instead. -->");
        builder.AppendLine("# API index\n");
        builder.AppendLine("Every component, its root element, its `data-slot`, and every parameter it accepts.");
        builder.AppendLine("`Class`, `ChildContent` and splatted attributes come from `UiComponentBase` and are");
        builder.AppendLine("omitted here — every component has all three.\n");
        builder.AppendLine("**Required** means `[EditorRequired]`: the component does not work without it.\n");
        var count = 0;
        foreach (var path in ToolApplication.RazorComponents(root))
        {
            count++;
            var text = File.ReadAllText(path);
            var markup = text.Split("@code", 2)[0];
            var slot = SlotRegex().Match(markup);
            var tag = RootTagRegex().Match(markup);
            builder.AppendLine($"## `<{Path.GetFileNameWithoutExtension(path)}>`");
            var bits = new List<string>();
            if (tag.Success) bits.Add($"renders `<{tag.Groups[1].Value}>`");
            if (slot.Success) bits.Add($"`data-slot=\"{slot.Groups[1].Value}\"`");
            builder.AppendLine(bits.Count == 0 ? "_composition only_" : string.Join(" · ", bits));
            builder.AppendLine();
            var parameters = ParameterRegex().Matches(text);
            if (parameters.Count == 0) builder.AppendLine("_No parameters of its own._");
            else
            {
                builder.AppendLine("| Parameter | Type | Default | |");
                builder.AppendLine("|---|---|---|---|");
                foreach (Match parameter in parameters)
                {
                    var priorAttribute = text.LastIndexOf("[Parameter", Math.Max(0, parameter.Index - 1), StringComparison.Ordinal);
                    var declaration = priorAttribute < 0 ? string.Empty : text[priorAttribute..(parameter.Index + parameter.Length)];
                    var value = parameter.Groups[3].Value.Trim();
                    builder.AppendLine($"| `{parameter.Groups[2].Value}` | `{parameter.Groups[1].Value}` | {(value.Length == 0 ? "—" : $"`{value}`")} | {(declaration.Contains("EditorRequired", StringComparison.Ordinal) ? "**required**" : "")} |");
                }
            }
            builder.AppendLine();
        }
        var generated = builder.ToString().ReplaceLineEndings("\n").TrimEnd() + "\n";
        if (ToolApplication.CheckOnly(options))
        {
            if (!File.Exists(output) || File.ReadAllText(output).ReplaceLineEndings("\n") != generated)
            {
                Console.Error.WriteLine("API.md is out of date - run the gen-api command");
                return 1;
            }
            Console.WriteLine($"API.md up to date ({count} components)");
            return 0;
        }
        File.WriteAllText(output, generated, new UTF8Encoding(false));
        Console.WriteLine($"wrote skills/shadcn-unpoly/API.md ({count} components)");
        return 0;
    }

    public static int CheckGenerated(DirectoryInfo root, string[] options, string relativePath, string label)
    {
        var path = Path.Combine(root.FullName, relativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path) && !Directory.Exists(path))
        {
            Console.Error.WriteLine($"missing generated {label}: {relativePath}");
            return 1;
        }
        if (!ToolApplication.CheckOnly(options))
            Console.WriteLine($"{label} generation is source-driven; existing committed output retained");
        else
            Console.WriteLine($"{label} output present");
        return 0;
    }

    public static int GenerateIcons(DirectoryInfo root, string[] options)
    {
        var iconDirectory = Path.Combine(root.FullName, "node_modules", "lucide-static", "icons");
        var listPath = Path.Combine(root.FullName, "tools", "icons.txt");
        var outputPath = Path.Combine(root.FullName, "src", "Unpoly.Blazor.Shadcn", "LucideIcons.g.cs");
        var names = File.ReadLines(listPath).Select(line => line.Trim())
            .Where(line => line.Length > 0 && line[0] != '#').ToHashSet(StringComparer.Ordinal);
        var addIndex = Array.IndexOf(options, "--add");
        if (addIndex >= 0)
        {
            if (addIndex + 1 >= options.Length) return Error("--add requires one or more comma-separated icon names");
            foreach (var name in options[addIndex + 1].Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                _ = IconBody(iconDirectory, name);
                names.Add(name);
            }
            File.WriteAllText(listPath, string.Join('\n', names.Order(StringComparer.Ordinal)) + "\n", new UTF8Encoding(false));
        }

        var packagePath = Path.Combine(root.FullName, "node_modules", "lucide-static", "package.json");
        if (!File.Exists(packagePath)) return Error("lucide-static is missing; run npm ci first");
        using var package = JsonDocument.Parse(File.ReadAllText(packagePath));
        var version = package.RootElement.GetProperty("version").GetString() ?? "unknown";
        var lines = new List<string>
        {
            "// <auto-generated />", $"// Lucide v{version}, ISC licensed. Regenerate with the gen-icons .NET command.", "",
            "namespace Unpoly.Blazor.Shadcn;", "", "/// <summary>",
            "/// The Lucide glyphs this library ships, as the inner markup of a 24x24 icon. The",
            "/// &lt;svg&gt; wrapper belongs to <see cref=\"Components.Icon\"/>, so every icon is drawn",
            "/// the same way and one class restyles all of them.", "/// </summary>",
            "public static class LucideIcons", "{",
            "    /// <summary>Icon name (kebab-case, as on lucide.dev) to its inner SVG markup.</summary>",
            "    public static readonly IReadOnlyDictionary<string, string> All =",
            "        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)", "        {"
        };
        lines.AddRange(names.Order(StringComparer.Ordinal).Select(name => $"            [\"{name}\"] = \"\"\"{IconBody(iconDirectory, name)}\"\"\","));
        lines.AddRange(["        };", "}"]);
        var generated = string.Join('\n', lines) + "\n";
        if (ToolApplication.CheckOnly(options))
        {
            if (!File.Exists(outputPath) || File.ReadAllText(outputPath).ReplaceLineEndings("\n") != generated)
                return Error("LucideIcons.g.cs is stale - run the gen-icons .NET command");
            Console.WriteLine($"LucideIcons.g.cs up to date ({names.Count} icons)");
            return 0;
        }
        File.WriteAllText(outputPath, generated, new UTF8Encoding(false));
        Console.WriteLine($"wrote src/Unpoly.Blazor.Shadcn/LucideIcons.g.cs ({names.Count} icons)");
        return 0;
    }

    private static string IconBody(string iconDirectory, string name)
    {
        var path = Path.Combine(iconDirectory, name + ".svg");
        if (!File.Exists(path)) throw new InvalidOperationException($"no such lucide icon: {name} (looked in {iconDirectory})");
        var match = SvgBodyRegex().Match(File.ReadAllText(path));
        if (!match.Success) throw new InvalidOperationException($"{name}.svg is not shaped like an svg");
        return string.Join(' ', WhitespaceRegex().Split(match.Groups[1].Value.Trim()).Where(part => part.Length > 0));
    }

    private static int Error(string message) { Console.Error.WriteLine(message); return 1; }

    [GeneratedRegex("\\[Parameter(?:,\\s*EditorRequired)?\\]\\s*public\\s+([\\w<>?\\[\\]]+)\\s+(\\w+)\\s*\\{[^}]*\\}\\s*(?:=\\s*(.+?);)?(?=\\r?$)", RegexOptions.Multiline)]
    private static partial Regex ParameterRegex();
    [GeneratedRegex("data-slot=\"([^\"@]+)\"")]
    private static partial Regex SlotRegex();
    [GeneratedRegex("^\\s*<([a-z][\\w-]*)\\b", RegexOptions.Multiline)]
    private static partial Regex RootTagRegex();
    [GeneratedRegex("<svg\\b[^>]*>(.*)</svg>", RegexOptions.Singleline)]
    private static partial Regex SvgBodyRegex();
    [GeneratedRegex("\\s+")]
    private static partial Regex WhitespaceRegex();
}
