// <auto-generated />
// Lucide v1.34.0, ISC licensed. Regenerate with: python tools/gen_icons.py
// Add an icon with: python tools/gen_icons.py --add <name>

namespace Unpoly.Blazor.Shadcn;

/// <summary>
/// The Lucide glyphs this library ships, as the inner markup of a 24x24 icon. The
/// &lt;svg&gt; wrapper belongs to <see cref="Components.Icon"/>, so every icon is drawn
/// the same way and one class restyles all of them.
/// </summary>
public static class LucideIcons
{
    /// <summary>Icon name (kebab-case, as on lucide.dev) to its inner SVG markup.</summary>
    public static readonly IReadOnlyDictionary<string, string> All =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["arrow-down"] = """<path d="M12 5v14" /> <path d="m19 12-7 7-7-7" />""",
            ["arrow-left"] = """<path d="m12 19-7-7 7-7" /> <path d="M19 12H5" />""",
            ["arrow-right"] = """<path d="M5 12h14" /> <path d="m12 5 7 7-7 7" />""",
            ["arrow-up"] = """<path d="m5 12 7-7 7 7" /> <path d="M12 19V5" />""",
            ["calendar"] = """<path d="M8 2v3" /> <path d="M16 2v3" /> <rect x="3" y="3" width="18" height="18" rx="2" /> <path d="M3 9h18" />""",
            ["check"] = """<path d="M20 6 9 17l-5-5" />""",
            ["chevron-down"] = """<path d="m6 9 6 6 6-6" />""",
            ["chevron-left"] = """<path d="m15 18-6-6 6-6" />""",
            ["chevron-right"] = """<path d="m9 18 6-6-6-6" />""",
            ["chevron-up"] = """<path d="m18 15-6-6-6 6" />""",
            ["chevrons-left"] = """<path d="m11 17-5-5 5-5" /> <path d="m18 17-5-5 5-5" />""",
            ["chevrons-right"] = """<path d="m6 17 5-5-5-5" /> <path d="m13 17 5-5-5-5" />""",
            ["chevrons-up-down"] = """<path d="m7 15 5 5 5-5" /> <path d="m7 9 5-5 5 5" />""",
            ["circle"] = """<circle cx="12" cy="12" r="10" />""",
            ["circle-alert"] = """<circle cx="12" cy="12" r="10" /> <line x1="12" x2="12" y1="8" y2="12" /> <line x1="12" x2="12.01" y1="16" y2="16" />""",
            ["circle-check"] = """<circle cx="12" cy="12" r="10" /> <path d="m9 12 2 2 4-4" />""",
            ["circle-x"] = """<circle cx="12" cy="12" r="10" /> <path d="m15 9-6 6" /> <path d="m9 9 6 6" />""",
            ["copy"] = """<rect width="14" height="14" x="8" y="8" rx="2" ry="2" /> <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />""",
            ["ellipsis"] = """<circle cx="12" cy="12" r="1" /> <circle cx="19" cy="12" r="1" /> <circle cx="5" cy="12" r="1" />""",
            ["ellipsis-vertical"] = """<circle cx="12" cy="12" r="1" /> <circle cx="12" cy="5" r="1" /> <circle cx="12" cy="19" r="1" />""",
            ["external-link"] = """<path d="M15 3h6v6" /> <path d="M10 14 21 3" /> <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />""",
            ["eye"] = """<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" /> <circle cx="12" cy="12" r="3" />""",
            ["eye-off"] = """<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49" /> <path d="M14.084 14.158a3 3 0 0 1-4.242-4.242" /> <path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143" /> <path d="m2 2 20 20" />""",
            ["grip-vertical"] = """<circle cx="9" cy="12" r="1" /> <circle cx="9" cy="5" r="1" /> <circle cx="9" cy="19" r="1" /> <circle cx="15" cy="12" r="1" /> <circle cx="15" cy="5" r="1" /> <circle cx="15" cy="19" r="1" />""",
            ["info"] = """<circle cx="12" cy="12" r="10" /> <path d="M12 16v-4" /> <path d="M12 8h.01" />""",
            ["loader-circle"] = """<path d="M21 12a9 9 0 1 1-6.219-8.56" />""",
            ["menu"] = """<path d="M4 5h16" /> <path d="M4 12h16" /> <path d="M4 19h16" />""",
            ["minus"] = """<path d="M5 12h14" />""",
            ["panel-left"] = """<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="M9 3v18" />""",
            ["pencil"] = """<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" /> <path d="m15 5 4 4" />""",
            ["plus"] = """<path d="M5 12h14" /> <path d="M12 5v14" />""",
            ["search"] = """<path d="m21 21-4.34-4.34" /> <circle cx="11" cy="11" r="8" />""",
            ["settings"] = """<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" /> <circle cx="12" cy="12" r="3" />""",
            ["trash-2"] = """<path d="M10 11v6" /> <path d="M14 11v6" /> <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" /> <path d="M3 6h18" /> <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />""",
            ["triangle-alert"] = """<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" /> <path d="M12 9v4" /> <path d="M12 17h.01" />""",
            ["upload"] = """<path d="M12 3v12" /> <path d="m17 8-5-5-5 5" /> <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />""",
            ["x"] = """<path d="M18 6 6 18" /> <path d="m6 6 12 12" />""",
        };
}
