#!/usr/bin/env python3
"""Generates themes/*.css from tweakcn's theme registry.

Same reason the component classes are generated: a palette retyped from a screenshot is a palette
that drifts, and nobody reviewing it can tell whether a value is deliberate or a typo. These come
from the registry that published them, and refreshing one is a diff.

    python tools/gen_themes.py            # rewrite themes/
    python tools/gen_themes.py --check    # CI: fail if a theme is stale

A theme is written as a [data-theme="name"] block so several can be loaded at once and switched by
an attribute. An app that ships one puts data-theme on <html>.
"""
import json
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'themes'
REGISTRY = 'https://tweakcn.com/r/themes/{name}.json'

# Chosen for how well each sits with shadcn's own shapes rather than for novelty. The note is
# printed into the file so a reader knows what they are looking at without opening the site.
THEMES = {
    'vercel': 'Black and white, sharp. The house style shadcn itself grew out of.',
    'supabase': 'Neon green on near-white. High contrast, unmistakably a developer tool.',
    'modern-minimal': 'Clean blue on pure white. The closest to shadcn default with a colour.',
    'notebook': 'Heavy borders on paper. The opposite of this library default, on purpose.',
}

# Variables this port does not use. Carrying them would imply they do something.
IGNORED = {'font-sans', 'font-serif', 'font-mono', 'letter-spacing', 'spacing', 'tracking-normal',
           'shadow-color', 'shadow-opacity', 'shadow-blur', 'shadow-spread', 'shadow-offset-x',
           'shadow-offset-y', 'shadow-2xs', 'shadow-xs', 'shadow-sm', 'shadow', 'shadow-md',
           'shadow-lg', 'shadow-xl', 'shadow-2xl'}

# Ours, derived from the theme's own values rather than invented.
def derived(light: dict) -> dict:
    radius = light.get('radius', '0.625rem')
    return {
        'radius-control': f'calc({radius} - 2px)',
    }


def fetch(name: str) -> dict:
    with urllib.request.urlopen(REGISTRY.format(name=name), timeout=30) as r:
        return json.load(r)


def block(selector: str, values: dict, indent='    ') -> str:
    lines = [f'{selector} {{']
    for k, v in values.items():
        lines.append(f'{indent}--{k}: {v};')
    lines.append('}')
    return '\n'.join(lines)


def render(name: str, note: str, data: dict) -> str:
    vars_ = data['cssVars']
    light = {k: v for k, v in vars_.get('light', {}).items() if k not in IGNORED}
    dark = {k: v for k, v in vars_.get('dark', {}).items() if k not in IGNORED}
    light.update(derived(light))

    head = (
        f'/* {data.get("name", name)} — {note}\n'
        f'   ==========================================================================================\n'
        f'   GENERATED by tools/gen_themes.py from {REGISTRY.format(name=name)}\n'
        f'   Do not edit; change the preset or the generator.\n\n'
        f'   Scoped to [data-theme] rather than :root so several themes can be loaded at once and\n'
        f'   switched by an attribute. An app that ships one theme puts the attribute on <html>. */\n\n'
    )

    parts = [head, block(f'[data-theme="{name}"]', light), '']
    if dark:
        parts += [block(f'[data-theme="{name}"].dark,\n[data-theme="{name}"] .dark', dark), '']
    return '\n'.join(parts)


def main() -> int:
    OUT.mkdir(exist_ok=True)
    check = '--check' in sys.argv
    stale = []

    for name, note in THEMES.items():
        path = OUT / f'{name}.css'
        if check:
            if not path.exists():
                stale.append(name)
                continue
            # Comparing against the live registry would make CI need the network and fail on a
            # preset the author changed. The committed file is the contract; only its presence
            # and shape are checked here.
            text = path.read_text(encoding='utf-8')
            if 'GENERATED by tools/gen_themes.py' not in text:
                stale.append(name)
            continue

        data = fetch(name)
        path.write_text(render(name, note, data), encoding='utf-8')
        print(f'  {name}.css')

    if check:
        if stale:
            print('themes missing or hand-edited: ' + ', '.join(stale), file=sys.stderr)
            return 1
        print(f'themes present ({len(THEMES)})')
        return 0

    print(f'wrote {len(THEMES)} themes')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
