#!/usr/bin/env python3
"""Generates LucideIcons.g.cs from the lucide-static package.

Lucide ships 2000+ icons. Emitting all of them would put half a megabyte of string data in an
assembly that every consumer loads, to serve the thirty icons a UI actually uses — so the set is
explicit and committed, and adding one is a reviewable diff:

    npm i                                     # once
    python tools/gen_icons.py                 # regenerate from icons.txt
    python tools/gen_icons.py --add trash-2   # add an icon and regenerate
    python tools/gen_icons.py --check         # CI: fail if the file is stale

The generated markup is the icon's children only. The <svg> wrapper — 24x24, fill none,
stroke currentColor, width 2, round caps — belongs to <Icon> so every icon is drawn the same way
and one class can restyle all of them, which is exactly what lucide-react does.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS_DIR = ROOT / 'node_modules' / 'lucide-static' / 'icons'
LIST = ROOT / 'tools' / 'icons.txt'
OUT = ROOT / 'src' / 'Unpoly.Blazor.Shadcn' / 'LucideIcons.g.cs'

# Everything between the <svg …> and </svg>, whitespace collapsed onto one line.
INNER = re.compile(r'<svg\b[^>]*>(.*)</svg>', re.S)


def body(name: str) -> str:
    path = ICONS_DIR / f'{name}.svg'
    if not path.exists():
        raise SystemExit(f'no such lucide icon: {name} (looked in {ICONS_DIR})')
    m = INNER.search(path.read_text(encoding='utf-8'))
    if not m:
        raise SystemExit(f'{name}.svg is not shaped like an svg')
    return ' '.join(m.group(1).split())


def version() -> str:
    pkg = ROOT / 'node_modules' / 'lucide-static' / 'package.json'
    m = re.search(r'"version":\s*"([^"]+)"', pkg.read_text(encoding='utf-8'))
    return m.group(1) if m else 'unknown'


def render(names):
    lines = [
        '// <auto-generated />',
        f'// Lucide v{version()}, ISC licensed. Regenerate with: python tools/gen_icons.py',
        '// Add an icon with: python tools/gen_icons.py --add <name>',
        '',
        'namespace Unpoly.Blazor.Shadcn;',
        '',
        '/// <summary>',
        '/// The Lucide glyphs this library ships, as the inner markup of a 24x24 icon. The',
        '/// &lt;svg&gt; wrapper belongs to <see cref="Components.Icon"/>, so every icon is drawn',
        '/// the same way and one class restyles all of them.',
        '/// </summary>',
        'public static class LucideIcons',
        '{',
        '    /// <summary>Icon name (kebab-case, as on lucide.dev) to its inner SVG markup.</summary>',
        '    public static readonly IReadOnlyDictionary<string, string> All =',
        '        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)',
        '        {',
    ]
    for n in names:
        lines.append(f'            ["{n}"] = """{body(n)}""",')
    lines += [
        '        };',
        '}',
    ]
    return '\n'.join(lines) + '\n'


def main():
    names = sorted({l.strip() for l in LIST.read_text(encoding='utf-8').splitlines()
                    if l.strip() and not l.startswith('#')})

    if '--add' in sys.argv:
        added = sys.argv[sys.argv.index('--add') + 1].split(',')
        for a in added:
            body(a.strip())          # fail before writing if the name is wrong
        names = sorted(set(names) | {a.strip() for a in added})
        LIST.write_text('\n'.join(names) + '\n', encoding='utf-8')
        print(f'added {", ".join(added)}')

    text = render(names)

    if '--check' in sys.argv:
        current = OUT.read_text(encoding='utf-8') if OUT.exists() else ''
        if current != text:
            print('LucideIcons.g.cs is stale — run: python tools/gen_icons.py', file=sys.stderr)
            return 1
        print(f'LucideIcons.g.cs up to date ({len(names)} icons)')
        return 0

    OUT.write_text(text, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} ({len(names)} icons)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
