#!/usr/bin/env python3
"""Regenerates skills/shadcn-unpoly/API.md from the components themselves.

A hand-written API table is a lie waiting to happen: someone adds a parameter, nobody edits the
doc, and the next agent writes markup against a signature that no longer exists. This reads the
.razor files instead, so the table is wrong only if the source is.

    python tools/gen_api.py            # rewrite API.md
    python tools/gen_api.py --check    # exit 1 if it is out of date (CI runs this)
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
COMPONENTS = ROOT / 'src' / 'Unpoly.Blazor.Shadcn' / 'Components'
OUT = ROOT / 'skills' / 'shadcn-unpoly' / 'API.md'

PARAM = re.compile(
    r'\[Parameter(?:,\s*EditorRequired)?\]\s*public\s+([\w<>?\[\]]+)\s+(\w+)\s*\{[^}]*\}'
    r'(?:\s*=\s*(.+?);)?$',
    re.M)
REQUIRED = re.compile(r'\[Parameter,\s*EditorRequired\]')
SLOT = re.compile(r'data-slot="([^"@]+)"')
ROOT_TAG = re.compile(r'^\s*<([a-z][\w-]*)\b', re.M)


def parse(path: pathlib.Path):
    text = path.read_text(encoding='utf-8')
    markup = text.split('@code', 1)[0]

    slot = SLOT.search(markup)
    tag = ROOT_TAG.search(markup)

    params = []
    for m in PARAM.finditer(text):
        line_start = text.rfind('[Parameter', 0, m.start())
        decl = text[line_start:m.end()]
        params.append({
            'type': m.group(1),
            'name': m.group(2),
            'default': (m.group(3) or '').strip() or None,
            'required': bool(REQUIRED.search(decl)),
        })

    return {
        'name': path.stem,
        'slot': slot.group(1) if slot else None,
        'tag': tag.group(1) if tag else None,
        'params': params,
    }


def render(components):
    lines = [
        '<!-- GENERATED by tools/gen_api.py — do not edit. Run the script instead. -->',
        '# API index',
        '',
        'Every component, its root element, its `data-slot`, and every parameter it accepts.',
        '`Class`, `ChildContent` and splatted attributes come from `UiComponentBase` and are',
        'omitted here — every component has all three.',
        '',
        '**Required** means `[EditorRequired]`: the component does not work without it.',
        '',
    ]
    for c in components:
        head = f'## `<{c["name"]}>`'
        lines.append(head)
        bits = []
        if c['tag']:
            bits.append(f'renders `<{c["tag"]}>`')
        if c['slot']:
            bits.append(f'`data-slot="{c["slot"]}"`')
        lines.append(' · '.join(bits) if bits else '_composition only_')
        lines.append('')
        own = [p for p in c['params']]
        if own:
            lines.append('| Parameter | Type | Default | |')
            lines.append('|---|---|---|---|')
            for p in own:
                default = f'`{p["default"]}`' if p['default'] else '—'
                mark = '**required**' if p['required'] else ''
                lines.append(f'| `{p["name"]}` | `{p["type"]}` | {default} | {mark} |')
        else:
            lines.append('_No parameters of its own._')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def main():
    components = sorted((parse(p) for p in COMPONENTS.glob('*.razor')), key=lambda c: c['name'])
    text = render(components)

    if '--check' in sys.argv:
        current = OUT.read_text(encoding='utf-8') if OUT.exists() else ''
        if current != text:
            print('API.md is out of date — run: python tools/gen_api.py', file=sys.stderr)
            return 1
        print(f'API.md up to date ({len(components)} components)')
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} ({len(components)} components)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
